---
- name: Restart node_exporter
  become: true
  systemd:
    name: node_exporter
    state: restarted

- name: Start node_exporter
  become: true
  systemd:
    name: node_exporter
    state: started

- name: Stop node_exporter
  become: true
  systemd:
    name: node_exporter
    state: stopped

- name: Enable node_exporter
  become: true
  systemd:
    name: node_exporter
    enabled: yes