---
- name: Restart {{node_exporter_service_name}}
  become: true
  systemd:
    name: {{node_exporter_service_name}}
    state: restarted

- name: Start {{node_exporter_service_name}}
  become: true
  systemd:
    name: {{node_exporter_service_name}}
    state: started

- name: Stop {{node_exporter_service_name}}
  become: true
  systemd:
    name: {{node_exporter_service_name}}
    state: stopped

- name: Enable {{node_exporter_service_name}}
  become: true
  systemd:
    name: {{node_exporter_service_name}}
    enabled: yes