galaxy_info:
  author: MDN
  description: "A role to install and configure Node Exporter"
  company: MDN
  license: ""
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: CentOS
      versions:
        - 7
        - 8
dependencies: []
