---
- name: Installing Node Exporter
  import_tasks: install.yaml

- name: Config and start Node Exporter
  import_tasks: config.yaml

- name: Enable and start node exporter
  systemd:
    name: "{{node_exporter_service_name}}" 
    enabled: true
    state: started